// 地圖標籤中文對照
export const CITY_NAMES_ZH: Record<string, string> = {
  "Tokyo": "東京",
  "Osaka": "大阪",
  "Nagoya": "名古屋",
  "Yokohama": "橫濱",
  "Sapporo": "札幌",
  "Fukuoka": "福岡",
  "Kyoto": "京都",
  "Kobe": "神戶",
  "Seoul": "首爾",
  "Busan": "釜山",
  "Incheon": "仁川",
  "Pyongyang": "平壤",
  "Beijing": "北京",
  "Shanghai": "上海",
  "Guangzhou": "廣州",
  "Shenzhen": "深圳",
  "Hong Kong": "香港",
  "Taipei": "台北",
  "Kaohsiung": "高雄",
  "Taichung": "台中",
  "Macau": "澳門",
  "Ulaanbaatar": "烏蘭巴托",
  "Chengdu": "成都",
  "Chongqing": "重慶",
  "Wuhan": "武漢",
  "Nanjing": "南京",
  "Xi'an": "西安",
  "Hangzhou": "杭州",
  "Shenyang": "瀋陽",
  "Harbin": "哈爾濱",
  "Tianjin": "天津",
  "Qingdao": "青島",
  "Singapore": "新加坡",
  "Bangkok": "曼谷",
  "Jakarta": "雅加達",
  "Manila": "馬尼拉",
  "Hanoi": "河內",
  "Ho Chi Minh City": "胡志明市",
  "Kuala Lumpur": "吉隆坡",
  "Yangon": "仰光",
  "Phnom Penh": "金邊",
  "Vientiane": "永珍",
  "Bandung": "萬隆",
  "Surabaya": "泗水",
  "Cebu": "宿霧",
  "Davao": "達沃",
  "Chiang Mai": "清邁",
  "Medan": "棉蘭",
  "Bali": "峇里島",
  "Denpasar": "登巴薩",
  "Brunei": "汶萊",
  "Bandar Seri Begawan": "斯里巴卡旺",
  "Mumbai": "孟買",
  "Delhi": "德里",
  "New Delhi": "新德里",
  "Kolkata": "加爾各答",
  "Chennai": "清奈",
  "Bangalore": "班加羅爾",
  "Hyderabad": "海得拉巴",
  "Karachi": "喀拉蚩",
  "Lahore": "拉合爾",
  "Islamabad": "伊斯蘭堡",
  "Dhaka": "達卡",
  "Colombo": "可倫坡",
  "Kathmandu": "加德滿都",
  "Thimphu": "廷布",
  "Male": "馬列",
  "Chittagong": "吉大港",
  "Pune": "浦那",
  "Ahmedabad": "阿美達巴德",
  "Dubai": "杜拜",
  "Abu Dhabi": "阿布達比",
  "Riyadh": "利雅德",
  "Jeddah": "吉達",
  "Doha": "杜哈",
  "Kuwait City": "科威特城",
  "Muscat": "馬斯喀特",
  "Manama": "麥納麥",
  "Tehran": "德黑蘭",
  "Baghdad": "巴格達",
  "Amman": "安曼",
  "Beirut": "貝魯特",
  "Damascus": "大馬士革",
  "Jerusalem": "耶路撒冷",
  "Tel Aviv": "特拉維夫",
  "Ankara": "安卡拉",
  "Istanbul": "伊斯坦堡",
  "Baku": "巴庫",
  "Yerevan": "葉里溫",
  "Tbilisi": "提比里斯",
  "London": "倫敦",
  "Paris": "巴黎",
  "Berlin": "柏林",
  "Madrid": "馬德里",
  "Rome": "羅馬",
  "Amsterdam": "阿姆斯特丹",
  "Brussels": "布魯塞爾",
  "Vienna": "維也納",
  "Zurich": "蘇黎世",
  "Geneva": "日內瓦",
  "Munich": "慕尼黑",
  "Hamburg": "漢堡",
  "Frankfurt": "法蘭克福",
  "Milan": "米蘭",
  "Barcelona": "巴塞隆納",
  "Lisbon": "里斯本",
  "Dublin": "都柏林",
  "Stockholm": "斯德哥爾摩",
  "Oslo": "奧斯陸",
  "Copenhagen": "哥本哈根",
  "Helsinki": "赫爾辛基",
  "Warsaw": "華沙",
  "Prague": "布拉格",
  "Budapest": "布達佩斯",
  "Athens": "雅典",
  "Bucharest": "布加勒斯特",
  "Sofia": "索菲亞",
  "Belgrade": "貝爾格勒",
  "Zagreb": "札格瑞布",
  "Moscow": "莫斯科",
  "Saint Petersburg": "聖彼得堡",
  "Kiev": "基輔",
  "Kyiv": "基輔",
  "Minsk": "明斯克",
  "Vilnius": "維爾紐斯",
  "Riga": "里加",
  "Tallinn": "塔林",
  "Edinburgh": "愛丁堡",
  "Manchester": "曼徹斯特",
  "Birmingham": "伯明罕",
  "Glasgow": "格拉斯哥",
  "Liverpool": "利物浦",
  "Rotterdam": "鹿特丹",
  "Antwerp": "安特衛普",
  "Luxembourg": "盧森堡",
  "Monaco": "摩納哥",
  "Venice": "威尼斯",
  "Florence": "佛羅倫斯",
  "Naples": "那不勒斯",
  "Marseille": "馬賽",
  "Lyon": "里昂",
  "Nice": "尼斯",
  "Porto": "波多",
  "Seville": "塞維亞",
  "Valencia": "瓦倫西亞",
  "Malta": "馬爾他",
  "Reykjavik": "雷克雅維克",
  "New York": "紐約",
  "Los Angeles": "洛杉磯",
  "Chicago": "芝加哥",
  "Houston": "休士頓",
  "Phoenix": "鳳凰城",
  "Philadelphia": "費城",
  "San Antonio": "聖安東尼奧",
  "San Diego": "聖地牙哥",
  "Dallas": "達拉斯",
  "San Jose": "聖荷西",
  "San Francisco": "舊金山",
  "Seattle": "西雅圖",
  "Denver": "丹佛",
  "Boston": "波士頓",
  "Miami": "邁阿密",
  "Atlanta": "亞特蘭大",
  "Detroit": "底特律",
  "Minneapolis": "明尼阿波利斯",
  "Washington": "華盛頓",
  "Las Vegas": "拉斯維加斯",
  "Portland": "波特蘭",
  "New Orleans": "紐奧良",
  "Nashville": "納什維爾",
  "Toronto": "多倫多",
  "Montreal": "蒙特婁",
  "Vancouver": "溫哥華",
  "Calgary": "卡加利",
  "Ottawa": "渥太華",
  "Edmonton": "艾德蒙頓",
  "Mexico City": "墨西哥城",
  "Guadalajara": "瓜達拉哈拉",
  "Monterrey": "蒙特雷",
  "Cancun": "坎昆",
  "Havana": "哈瓦那",
  "Panama City": "巴拿馬城",
  "San Juan": "聖胡安",
  "Guatemala City": "瓜地馬拉市",
  "San Jose (CR)": "聖荷西",
  "São Paulo": "聖保羅",
  "Rio de Janeiro": "里約熱內盧",
  "Buenos Aires": "布宜諾斯艾利斯",
  "Lima": "利馬",
  "Bogotá": "波哥大",
  "Santiago": "聖地牙哥",
  "Caracas": "卡拉卡斯",
  "Quito": "基多",
  "La Paz": "拉巴斯",
  "Brasília": "巴西利亞",
  "Salvador": "薩爾瓦多",
  "Fortaleza": "福塔萊薩",
  "Montevideo": "蒙特維多",
  "Asunción": "亞松森",
  "Medellín": "麥德林",
  "Guayaquil": "瓜亞基爾",
  "Belo Horizonte": "美景市",
  "Cairo": "開羅",
  "Lagos": "拉各斯",
  "Johannesburg": "約翰尼斯堡",
  "Nairobi": "奈洛比",
  "Casablanca": "卡薩布蘭卡",
  "Cape Town": "開普敦",
  "Addis Ababa": "阿迪斯阿貝巴",
  "Accra": "阿克拉",
  "Dakar": "達卡",
  "Dar es Salaam": "三蘭港",
  "Khartoum": "喀土穆",
  "Algiers": "阿爾及爾",
  "Tunis": "突尼斯",
  "Tripoli": "的黎波里",
  "Abidjan": "阿比讓",
  "Kinshasa": "金夏沙",
  "Luanda": "魯安達",
  "Kampala": "坎帕拉",
  "Harare": "哈拉雷",
  "Lusaka": "路沙卡",
  "Durban": "德班",
  "Pretoria": "普利托利亞",
  "Alexandria": "亞歷山卓",
  "Sydney": "雪梨",
  "Melbourne": "墨爾本",
  "Brisbane": "布里斯本",
  "Perth": "伯斯",
  "Auckland": "奧克蘭",
  "Wellington": "威靈頓",
  "Christchurch": "基督城",
  "Adelaide": "阿德雷德",
  "Canberra": "坎培拉",
  "Honolulu": "檀香山",
  "Suva": "蘇瓦",
  "Port Moresby": "莫士比港",
  "Noumea": "努美阿",
  "Papeete": "巴比提",
  "Bamako": "巴馬科",
  "Ouagadougou": "瓦加杜古",
  "Conakry": "科納克里",
  "Lomé": "洛美",
  "Kumasi": "庫馬西",
  "Brazzaville": "布拉薩",
  "Yaoundé": "雅溫德",
  "Yaounde": "雅溫德",
  "Douala": "杜阿拉",
  "Kano": "卡諾",
  "Kaduna": "卡杜納",
  "Ibadan": "伊巴丹",
  "Abuja": "阿布加",
  "Onitsha": "奧尼查",
  "Mbuji-Mayi": "姆布吉馬伊",
  "Khartoum ": "喀土穆",
  "Ōsaka": "大阪",
  "Kōbe": "神戶",
  "Bogota": "波哥大",
  "Bengaluru": "班加羅爾",
  "Amaravati": "阿馬拉瓦蒂",
  "Haora": "豪拉",
  "Shenyeng": "瀋陽",
  "St.  Petersburg": "聖彼得堡",
  "Chattogram": "吉大港",
  "Dongguan": "東莞",
  "Washington,  D.C.": "華盛頓",
  "Xian": "西安",
  "Porto Alegre": "阿雷格里港",
  "New Taipei": "新北",
  "Surat": "蘇拉特",
  "Hechi": "河池",
  "Montréal": "蒙特婁",
  "Guiyang": "貴陽",
  "Recife": "勒西菲",
  "Ürümqi": "烏魯木齊",
  "Zhangzhou": "漳州",
  "Kabul": "喀布爾",
  "Changchun": "長春",
  "Dalian": "大連",
  "Kanpur": "坎普爾",
  "Curitiba": "古里提巴",
  "Zibo": "淄博",
  "Irvine": "爾灣",
  "Benoni": "伯諾尼",
  "Stuttgart": "斯圖加特",
  "Kunming": "昆明",
  "Jaipur": "齋浦爾",
  "Taiyuan": "太原",
  "Jinan": "濟南",
  "Campinas": "坎皮納斯",
  "Quezon City": "奎松市",
  "Katowice": "卡托維茲",
  "Aleppo": "阿勒頗",
  "Lucknow": "勒克瑙",
  "Giza": "吉薩",
  "Zhengzhou": "鄭州",
  "Faisalabad": "費薩拉巴德",
  "Fuzhou": "福州",
  "Changsha": "長沙",
  "İzmir": "伊茲密爾",
  "Xiangtan": "湘潭",
  "Lanzhou": "蘭州",
  "Xiamen": "廈門",
  "George Town": "喬治市",
  "Mashhad": "馬什哈德",
  "Daegu": "大邱",
  "Nagpur": "那格浦爾",
  "Jinxi": "錦西",
  "Shijiazhuang": "石家莊",
  "Jilin": "吉林",
  "Omdurman": "恩圖曼",
  "Bekasi": "勿加泗",
  "Mannheim": "曼海姆",
  "Wenzhou": "溫州",
  "Nanchang": "南昌",
  "Tampa": "坦帕",
  "Baltimore": "巴爾的摩",
  "Cali": "卡利",
  "Sendai": "仙台",
  "St. Louis": "聖路易",
  "Puebla": "普埃布拉",
  "Tashkent": "塔什干",
  "Nanchong": "南充",
  "Nanning": "南寧",
  "Belém": "貝倫",
  "Patna": "巴特那",
  "Santo Domingo": "聖多明哥",
  "Zaozhuang": "棗莊",
  "Yantai": "煙台",
  "Santa Cruz": "聖克魯斯",
  "Xuzhou": "徐州",
  "Linyi": "臨沂",
  "Maracaibo": "馬拉開波",
  "Dammam": "達曼",
  "Haikou": "海口",
  "Hiroshima": "廣島",
  "Fort Lauderdale": "勞德代爾堡",
  "Long Beach": "長堤",
  "Baotou": "包頭",
  "Hefei": "合肥",
  "Indore": "印多爾",
  "Goiânia": "戈亞尼亞",
  "Sanaa": "沙那",
  "Port-au-Prince": "太子港",
  "Haiphong": "海防",
  "Suzhou": "蘇州",
  "Nanyang": "南陽",
  "Ningbo": "寧波",
  "Cleveland": "克里夫蘭",
  "Tangshan": "唐山",
  "Tainan": "台南",
  "Datong": "大同",
  "Saidu": "塞杜",
  "Rawalpindi": "拉瓦爾品第",
  "Pittsburgh": "匹茲堡",
  "Barranquilla": "巴蘭幾亞",
  "Shuyang": "沭陽",
  "Vadodara": "巴羅達",
  "Shangqiu": "商丘",
  "Manaus": "瑪瑙斯",
  "Wuxi": "無錫",
  "Palembang": "巨港",
  "San Bernardino": "聖貝納迪諾",
  "Essen": "埃森",
  "Bhopal": "博帕爾",
  "Hohhot": "呼和浩特",
  "Luoyang": "洛陽",
  "Santos": "桑托斯",
  "Jianmen": "江門",
  "Rabat": "拉巴特",
  "Vitória": "維多利亞",
  "Antananarivo": "安塔那那利佛",
  "Coimbatore": "哥印拜陀",
  "Daqing": "大慶",
  "Luan": "六安",
  "Wanzhou": "萬州",
  "Turin": "都靈",
  "Ludhiana": "盧迪亞納",
  "Qiqihar": "齊齊哈爾",
  "Anshan": "鞍山",
  "Cincinnati": "辛辛那提",
  "Zhongli": "中壢",
  "Handan": "邯鄲",
  "Taian": "泰安",
  "Isfahan": "伊斯法罕",
  "Sacramento": "沙加緬度",
  "Shantou": "汕頭",
  "Agra": "阿格拉",
  "Zhanjiang": "湛江",
  "Kalyan": "卡利揚",
  "Xiantao": "仙桃",
  "Weifang": "濰坊",
  "Khulna": "庫爾納",
  "Tijuana": "蒂華納",
  "Xinyang": "信陽",
  "Luzhou": "瀘州",
  "Toluca": "托盧卡",
  "Leeds": "里茲",
  "Vishakhapatnam": "維沙卡帕特南",
  "Multan": "木爾坦",
  "Kochi": "科欽",
  "Gujranwala": "古杰蘭瓦拉",
  "Oakland": "奧克蘭",
  "Niterói": "尼泰羅伊",
  "Ganzhou": "贛州",
  "Liuzhou": "柳州",
  "Bursa": "布爾薩",
  "Virginia Beach": "維吉尼亞海灘",
  "León": "萊昂",
  "Nasik": "納西克",
  "Fushun": "撫順",
  "Changde": "常德",
  "Kansas City": "堪薩斯城",
  "Daejeon": "大田",
  "Neijiang": "內江",
  "Quanzhou": "泉州",
  "Kharkiv": "哈爾科夫",
  "Córdoba": "科爾多瓦",
  "Huainan": "淮南",
  "Maputo": "馬普托",
  "Ft.  Worth": "沃斯堡",
  "Gwangju": "光州",
  "Kawasaki": "川崎",
  "Indianapolis": "印第安納波利斯",
  "San Salvador": "聖薩爾瓦多",
  "Suining": "遂寧",
  "Karaj": "卡拉季",
  "Tabriz": "大不里士",
  "The Hague": "海牙",
  "Meerut": "密拉特",
  "Mianyang": "綿陽",
  "Semarang": "三寶瓏",
  "Faridabad": "法里達巴德",
  "Novosibirsk": "新西伯利亞",
  "Milwaukee": "密爾瓦基",
  "Makkah": "麥加",
  "Maanshan": "馬鞍山",
  "Yiyang": "益陽",
  "Lubumbashi": "盧本巴希",
  "Varanasi": "瓦拉納西",
  "Orlando": "奧蘭多",
  "Ciudad Juárez": "華雷斯城",
  "Ghaziabad": "加濟阿巴德",
  "Heze": "菏澤",
  "Asansol": "阿桑索爾",
  "Changzhou": "常州",
  "Mosul": "摩蘇爾",
  "Yekaterinburg": "葉卡捷琳堡",
  "Peshawar": "白沙瓦",
  "Mandalay": "曼德勒",
  "Jamshedpur": "詹謝普爾",
  "Madurai": "馬杜賴",
  "Adana": "阿達納",
  "Sheffield": "雪菲爾",
  "Jabalpur": "賈巴爾普爾",
  "San José": "聖荷西",
  "Nizhny Novgorod": "下諾夫哥羅德",
  "Providence": "普羅維登斯",
  "Chifeng": "赤峰",
  "Duisburg": "杜伊斯堡",
  "Columbus": "哥倫布",
  "Huaiyin": "淮安",
  "Makassar": "望加錫",
  "Rajkot": "拉傑果德",
  "West Palm Beach": "西棕櫚灘",
  "Dhanbad": "丹巴德",
  "Mudangiang": "牡丹江",
  "Shiraz": "設拉子",
  "Huzhou": "湖州",
  "Tianshui": "天水",
  "Liupanshui": "六盤水",
  "Düsseldorf": "杜塞道夫",
  "Maoming": "茂名",
  "Amritsar": "阿姆利則",
  "Vila Velha": "韋利亞鎮",
  "Almaty": "阿拉木圖",
  "Warangal": "瓦朗加爾",
  "Rosario": "羅薩里奧",
  "Allahabad": "安拉阿巴德",
  "Benin City": "貝南城",
  "Jining": "濟寧",
  "Maceió": "馬塞約",
  "Abbottabad": "阿伯塔巴德",
  "Banghazi": "班加西",
  "Cilacap": "芝拉扎",
  "Raleigh": "羅里",
  "Austin": "奧斯汀",
  "Leshan": "樂山",
  "Shangrao": "上饒",
  "Torreón": "托雷翁",
  "Srinagar": "斯利那加",
  "Vijayawada": "維傑亞瓦達",
  "Samara": "薩馬拉",
  "Omsk": "鄂木斯克",
  "Nampo": "南浦",
  "Yulin": "榆林",
  "Xianyang": "咸陽",
  "Cagayan de Oro": "卡加延德奧羅",
  "Can Tho": "芹苴",
  "Barquisimeto": "巴基西梅托",
  "Kazan": "喀山",
  "Aurangabad": "奧蘭加巴德",
  "Nezahualcoyotl": "內薩瓦爾科約特爾",
  "Zürich": "蘇黎世",
  "Baoding": "保定",
  "Zigong": "自貢",
  "Sharjah": "沙迦",
  "Ankang": "安康",
  "Mogadishu": "摩加迪休",
  "Huambo": "萬博",
  "Ikare": "伊卡雷",
  "Bhilai": "比萊"
};
